# Generated by Django 5.2.6 on 2025-10-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='related',
            field=models.ManyToManyField(blank=True, to='main.dummymodel'),
        ),
    ]
