# Generated by Django 5.2.6 on 2025-10-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0013_cityproxy_countryproxy_regionproxy'),
        ('datoriLavoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='citta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.cityproxy', verbose_name='Città'),
        ),
    ]
